fix orphaned task

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -13,7 +13,7 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  test:
+  test-packages:
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
@@ -32,3 +32,16 @@ jobs:
       - name: Test ${{ matrix.package }}
         run: yarn test
         working-directory: packages/${{ matrix.package }}
+
+  test:
+    runs-on: ubuntu-latest
+    needs: test-packages
+    if: always()
+    steps:
+      - name: Check test results
+        run: |
+          if [ "${{ needs.test-packages.result }}" != "success" ]; then
+            echo "One or more tests failed"
+            exit 1
+          fi
+          echo "All tests passed"
